apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: achut15/react-app:latest  # Replace with your image
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: react-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Expose using NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: react-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: react-app-config
data:
  REACT_APP_FEATURE_FLAG: "true"  # Feature flag to enable or disable features
  REACT_APP_ENV: "production"  # The environment (e.g., development, production)
  REACT_APP_APP_NAME: "MyReactApp"  # Name of your application
  REACT_APP_LOG_LEVEL: "debug"  # Logging level (e.g., debug, info, error)
  REACT_APP_API_TIMEOUT: "5000"  # Timeout in milliseconds for API calls
  REACT_APP_MAX_RETRIES: "3"  # Max retries for API calls
  REACT_APP_VERSION: "1.0.0"  # Version of your app
